name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O 'master', asegúrate de poner el nombre correcto de tu rama

permissions:
  contents: write # Permiso necesario para que el bot pueda publicar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código del repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instala Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # O la versión que uses

      # 3. Instala las dependencias y construye el proyecto
      - name: Install and Build
        run: |
          npm install
          npm run build
          # Truco: Crear archivo .nojekyll para que GitHub no ignore los archivos de Next.js
          touch out/.nojekyll 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out  # <--- CAMBIO CLAVE: Next.js exporta a 'out'
          branch: gh-pages